### ISSUE TITLE
Sharpsign less-than is not conforming to standard

### ISSUE THREAD

**Issue by Harleqin** [mmontone/cl-sparql#1]
You should not define `#<`, as it is already defined to be invalid reader syntax.  http://clhs.lisp.se/Body/02_dht.htm

**Comment by mmontone** [comment]
You are right. Will change to something else.

**Comment by mmontone** [comment]
`#u<url>` ? Do you have some other suggestion?

**Comment by Harleqin** [comment]
Seems fine to me, but I'm not the authority ^^.

**Comment by mmontone** [comment]
I've changed uri syntax to #u<rdf:type>
